deploy/roles/reportable-condition-notifier/create.sql
deploy/roles/reportable-condition-notifier/grants.sql
deploy/shipping/views.sql
revert/roles/reportable-condition-notifier/create.sql
revert/roles/reportable-condition-notifier/grants.sql
revert/shipping/views.sql
sqitch.plan
templates/revert/pg.tmpl
templates/verify/pg.tmpl
verify/roles/reportable-condition-notifier/create.sql
verify/roles/reportable-condition-notifier/grants.sql
verify/shipping/views.sql

This is the VIEW version of https://trello.com/c/coA6Z3dR/11-reportable-condition-notifications. It includes seattleflu/id3c/pull/47
Create and assign grants to the reportable condition
notifier role.

Create reportable condition notifier role

---

deploy/shipping/views.sql
deploy/shipping/views@2019-09-12.sql
revert/shipping/views@2019-09-12.sql
sqitch.plan
verify/shipping/views@2019-09-12.sql

Rework the `shipping.reportable_condition_v1` view to include manifest
sheet and file name from the `sample` details.

views: update reportable condition view

---

deploy/shipping/views@2019-09-27.sql
revert/shipping/views.sql
revert/shipping/views@2019-09-27.sql
sqitch.plan
verify/shipping/views@2019-09-27.sql

Port over shipping view for flu assembly jobs from https://github.com/seattleflu/id3c/pull/57

Shipping view for flu assembly jobs

---

.gitignore
Pipfile
Pipfile.lock
dev/mypy
mypy.ini

As we add more code to this repo, it'll be nice to have type checks to
catch errors.

Type checking with mypy

---

Pipfile.lock
lib/seattleflu/id3c/api/datastore.py
lib/seattleflu/id3c/api/routes.py
schema/deploy/roles/return-results-exporter/create.sql
schema/deploy/roles/return-results-exporter/grants.sql
schema/deploy/shipping/views@2019-10-18.sql
schema/revert/roles/return-results-exporter/create.sql
schema/revert/roles/return-results-exporter/grants.sql
schema/revert/shipping/views.sql
schema/revert/shipping/views@2019-10-18.sql
schema/sqitch.plan
schema/verify/roles/return-results-exporter/create.sql
schema/verify/roles/return-results-exporter/grants.sql
schema/verify/shipping/views@2019-10-18.sql
setup.py

Creates shipping view for return of results on the SFS website. 
This view includes `barcode`, `status`, `organisms_present`, and `organisms_absent`. 
This does not include sequencing status/info yet.

Return results view

---

clinical/uw/.gitignore
clinical/uw/README.md
clinical/uw/Snakefile
clinical/uw/id3c-geocode.yaml
clinical/uw/workflow-schema.yaml
lib/seattleflu/id3c/cli/command/__init__.py
lib/seattleflu/id3c/cli/command/clinical.py
lib/seattleflu/id3c/cli/command/etl/clinical.py
lib/seattleflu/id3c/cli/command/longitudinal.py

Explanations in the commit messages.
This is important to do by tomorrow so we can load it and then Mike can re-run his models by the end of the week and then we can deploy the current conditions map.

Handling new clinical dataset from UW

---

schema/deploy/warehouse/target/data@2020-01-15c.sql
schema/sqitch.plan

Spurred by @famulare noticing this over the weekend and [bringing it up on Slack](https://seattle-flu-study.slack.com/archives/CCAEWSFTK/p1579467413018800).

Link Ellume's targets to our organisms

---

schema/deploy/warehouse/target/data@2020-02-21.sql
schema/sqitch.plan

Add snomed RSV target used in Cepheid results

Cepheid RSV target

---

schema/deploy/warehouse/target/data@2020-02-26.sql
schema/sqitch.plan

Links new target `nCoV` to new organism `Human_coronavirus.2019`
Deletes the previously created organism `Human_coronavirus.2019_nCoV`.

Link nCoV target to organism

---

lib/seattleflu/id3c/cli/command/etl/__init__.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_asymptomatic_swab_n_send.py

Very similar to old swab-n-send project, just had to edit some field names and delete fields that are not present in the asymptomatic project.

Asymptomatic swab n send

---

lib/seattleflu/id3c/cli/command/etl/__init__.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
lib/seattleflu/id3c/cli/command/etl/redcap_map.py
schema/deploy/warehouse/site/data@2020-03-09.sql
schema/revert/warehouse/site/data.sql
schema/revert/warehouse/site/data@2020-03-09.sql
schema/sqitch.plan
schema/verify/warehouse/site/data@2020-03-09.sql

My remaining question is whether we need to decode the answers within `QuestionnaireResponse` or do we just leave them as codes.
If we do want to decode them, what do we decode them to? I'm assuming we will be returning these to the study group, so do we want to make them even more readable?

Scan redcap etl

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

Instead of using `identifer like`, join with `warehouse.identifier`
do directly compare with citext barcode for case-insensitivity and
indexed operation.

etl redcap-det uw-retro: fix sample barcode lookup

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

Add an additional discharge disposition key to the UW Retrospective
REDCap-DET ETL.

redcap-det uw-retrospectives: Add discharge disposition

---

lib/seattleflu/id3c/cli/command/reportable_conditions.py

Aim for being useful to the humans currently doing the reporting out.
These notifications originally used embedded JSON blobs because Audere
wanted requested it so they could automate processing of them, but AFAIK
that never happened and Audere's involvement in this is now ancient
history.
---
Screenshot of two example notifications with this change.

Improve legibility of reportable condition Slack notifications

---

schema/deploy/shipping/views.sql
schema/deploy/shipping/views@2020-03-29b.sql
schema/revert/shipping/views@2020-03-29b.sql
schema/sqitch.plan
schema/verify/shipping/views@2020-03-29b.sql

This view is made to pull all encounters from SCAN regardless of
whether they have a sample. This is made for Roy to pull the most
up-to-date demographic data for the SCAN project.

Create shipping.scan_encounters_v1 view

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

Add a new encounter status code to our mapping logic.

etl redcap-det uw-retrospectives: Add encounter status

---

schema/deploy/shipping/views.sql
schema/deploy/shipping/views@2020-04-09c.sql
schema/revert/shipping/views@2020-04-09c.sql
schema/sqitch.plan
schema/verify/shipping/views@2020-04-09c.sql

Adds `symptoms_2` and `symptom_onset_2` to both `shipping.fhir_encounter_details_v2` and
`shipping.scan_encounters_v1`.

Add new symptoms to views

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py

This is a new question added to the `illness_questionnaire`.

etl redcap-det scan-en: add `ace` field to QuestionnairResponse

---

README.md
lib/seattleflu/id3c/cli/command/etl/__init__.py
lib/seattleflu/id3c/cli/command/etl/clinical.py

Update the clinical ETL pipeline with new mappings from values received from SCH. 
Add doctests.

Clinical sch

---

locations/data/seattle-neighborhood-svg/create-svgs
locations/data/seattle-neighborhood-svg/export-id3c-svg-paths

This was requested by Formative for their public-facing dashboard.

Create an SVG of Seattle neighborhoods

---

lib/seattleflu/id3c/api/routes.py
schema/deploy/shipping/views.sql
schema/deploy/shipping/views@2020-07-29.sql
schema/revert/shipping/views.sql
schema/revert/shipping/views@2020-07-29.sql
schema/sqitch.plan
schema/verify/shipping/views.sql
schema/verify/shipping/views@2020-07-29.sql

Formative requested that we include negative counts by day as well so they can calculate the percent positives.

SCAN Negative Counts

---

locations/Snakefile

Neighborhood district names

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
schema/deploy/warehouse/site/data@2020-08-27.sql
schema/revert/warehouse/site/data.sql
schema/revert/warehouse/site/data@2020-08-27.sql
schema/sqitch.plan
schema/verify/warehouse/site/data@2020-08-27.sql

Adds necessary changes to the SCAN ETL in order to ingest the new Husky project.

SCAN Husky REDCap

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py

The SCAN Husky project only uses post_collection_data_entry_qc to mark
"never-tested". So we need to rely on `nasal_swab_collection` instrument
to know that we have sample data to ingest.
Only rely on `nasal_swab_collection` if the record is from a kiosk
project, where the record does not have the ~`return_utm_barcode` field~ `back_end_mail_scans` instrument.

etl redcap-det scan: Update how to determine `specimen_received`

---

lib/seattleflu/id3c/cli/command/etl/__init__.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_asymptomatic_swab_n_send.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_and_home_flu.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

See details in commit messages.
Needs to be deployed with changes in ID3C core (https://github.com/seattleflu/id3c/pull/163)

Support repeating REDCap

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py

Adds a check to the start of the record instance loop to make sure that
we have the data we need to create an ENCOUNTER encounter.
Otherwise, skip the record instance with a log entry at the DEBUG
level.
Switches instrument from test_fulfillment_form to test_order_survey
when looking for swab and send encounter to make the check
consistent with what is pulled for the encounter_date.
This commit also condenses some of the event type logic.
The 'Testing Determination - Internal' instrument does not capture a
date, so calculate encounter_date based on the repeat instance number
and the date that the first repeat instance represents for the project.

uw-reopening ETL: Check that encounter data exists

---

lib/seattleflu/id3c/cli/command/etl/__init__.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py

The is the ETL for the Childcare study.
This PR depends on seattleflu/id3c-customizations/pull/152

Add redcap_det_childcare.py for Childcare Study

---

lib/seattleflu/id3c/cli/command/reportable_conditions.py

hCoV-19 results for the Childcare also need to be sent to the new
`#ncov-reporting-childcare` channel because some members of the
Childcare study should not have access to the general `#ncov-reporting`
channel.
Due to time restrictions, this addition is done very lazily by
verifying all responses from Slack have a 200 status code. This does
mean that if one POST request fails, all of them will be sent again
on the next run of the notify command. The chance of this happening
seems pretty small, but we can revisit this at a later date if it
becomes a common issue.
EDIT: TODO:

reportable_conditions notify: add notifications to new Childcare channel

---

schema/deploy/shipping/views.sql
schema/revert/shipping/views.sql
schema/sqitch.plan

Feedback was that numeric, not double precision, is the better choice.
I have the sqitch tag in here with the thinking that this will be approved soon. If not I will remove it.

Handle valueDecimal items as numeric in view

---

schema/deploy/shipping/views@2020-10-28.sql
schema/deploy/shipping/views@2020-10-28b.sql
schema/revert/shipping/views@2020-10-28.sql
schema/revert/shipping/views@2020-10-28b.sql
schema/verify/shipping/views@2020-10-28.sql
schema/verify/shipping/views@2020-10-28b.sql

In my sqitch reworks yesterday and today I forgot to check in some files,
so this commit is adding them.

Add missing files related to preview 2 db reworks

---

lib/seattleflu/id3c/cli/command/etl/redcap.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_asymptomatic_swab_n_send.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_and_home_flu.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

Make minor renaming improvements.
This must be deployed in coordination with https://github.com/seattleflu/id3c/pull/180.

Minor renaming updates (in coordination with configurable cache changes)

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py

Update :func: `zipcode_map` to check if the provided *redcap_code* is an
emptry string to catch the edge case of when the zipcode field is empty.
This field may be an empty string if edited by internal SFS members
for participants that live outside the SCAN coverage zip codes. We've
been doing in person dropoffs for priority codes that can be outside of
the normal SCAN coverage.
There's no need to update the geocoding process because SmartyStreets
can handle address lookups without a zipcode.

etl redcap-det scan: Fix error when the zip code field is empty

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py

For the UW reopening ETL, accommodate an issue when REDCap
fails to set the `attestation_date` on the `daily_attestation`
instrument. When this case occurs, compute the encounter date
from the repeat instance. This is safe to do because the Musher
computes the instance from the date.
This is where Musher computes instance ID from the date: 
https://github.com/seattleflu/husky-musher/blob/35c1e7fd14cf12065e4bdc86626116053c6bd056/lib/husky_musher/utils/redcap.py#L183
I tested with this record from HCT. Right now it's a good one to test with because it's in the situation where attestation_date didn't get set.
id3c redcap-det generate --project-id=23854 "1818"

Compute encounter date from REDCap repeat instance

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py

Currently, when we see a warning logged from the UW Reopening ETL, we have
to go to the syslog and grep through to find the warning entry and then
find the associated record number. This takes a lot of time. This commit
logs the record ID and in some places the record instance ID for record
related warnings.
In the future when we have a structured logging solution, we will have a
different way to get the record context with the event.

Log record info with uw-reopening ETL warnings

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py

The revision is not being updated. Instead, I will pull all records.

Add surveillance questionnaire item for UW

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py

Adds two checks to warn if enrollment information for a participant
violates rules that would impact test invitations.

Add data quality checks in UW Reopening ETL

---

schema/deploy/roles/assembly-exporter/create.sql
schema/deploy/roles/assembly-exporter/grants.sql
schema/deploy/shipping/views@2021-03-18.sql
schema/revert/roles/assembly-exporter/create.sql
schema/revert/roles/assembly-exporter/grants.sql
schema/revert/shipping/views.sql
schema/revert/shipping/views@2021-03-18.sql
schema/sqitch.plan
schema/verify/roles/assembly-exporter/create.sql
schema/verify/roles/assembly-exporter/grants.sql
schema/verify/shipping/views@2021-03-18.sql

Create an "assembly-exporter" role and a new shipping view `shipping.genome_submission_metadata_v1`. 
For context, this is how I intend to use the view for submissions:
```sql
create temp table batch(nwgc_id text, sfs_sample_barcode text);
\copy batch ("$columns") from '"$1"' csv header
create temp view batch_export as (
select
nwgc_id,
sfs_sample_identifier,
sfs_sample_barcode,
collection_date,
swab_type,
source,
puma,
state
from batch
left join shipping.genome_submission_metadata_v1 using (sfs_sample_barcode)
order by nwgc_id
);
\copy (select * from batch_export) to pstdout with csv header
```

Assembly metadata

---

lib/seattleflu/id3c/cli/command/offer_uw_testing.py

REDCap's been intermittently throwing errors on record update, seemingly
due to larger quota sizes → more records to update.  Reduce the load on
REDCap by batching updates into several smaller chunks.

offer-uw-testing: Batch record updates to REDCap at 250 records/request

---

Pipfile
schema/deploy/roles/idle-session-disconnector/grants.sql
schema/deploy/roles/idle-session-disconnector/grants@2021-04-22.sql
schema/revert/roles/idle-session-disconnector/grants.sql
setup.py
tests/search-path.py
tests/sqitch-transactions.py

See commit messages for details. The test for proper transaction use was prompted by #223.

Tests for Sqitch change scripts

---

lib/seattleflu/id3c/cli/command/clinical.py

Update to CLI commands to add census tract and handle multiple files due to changes in Kaiser Permanente year 2 manifests.

Kaiser year 2

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py

We are postponing processing of enrollment records for the HCT migrated
records until the data issues with those record are resolved in REDCap. This is
causing warnings when there are DETs being processed for migrated records'
enrollment forms that do not have any non-enrollment forms filled out.
Each FHIR bundle with a patient resource must contain at least one encounter resource,
which typically would be covered because the enrollment itself counts as an encounter.
Because those are not being processed for migrated records there needs to be at least
one non-enrollment encounter to create a valid FHIR bundle. This change checks to make
sure that is the case before generating the FHIR bundle.

Skip HCT migrated records with no non-enrollment encounters

---

Pipfile.lock
lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

Updates to UW Retrospective ETL based on recently received REDCap data which includes new formatting for discharge disposition (including numeric codes) and new test result and encounter status values which already had existing value mapping.  To account for these changes in the ETL process, numeric codes are being stripped form the discharge disposition values, and mapping has been updated to include new values for test result and encounter status fields.

UW retrospective ETL updates

---

lib/seattleflu/id3c/cli/command/reportable_conditions.py

Remove Y3 childcare and ROSEY/Yakima schools from reporting Slack channels

reportable_conditions: remove childcare and ROSEY

---

Pipfile.lock
setup.py

Fix failing tests regression introduced by pytest==7.0.0: https://github.com/pytest-dev/pytest/issues/9608#issuecomment-1030355395
Fix fatal exception caused by changes in the way pandas' NATypes are converted to JSON: https://seattle-flu-study.slack.com/archives/CLCKA5AKW/p1644352812859719

Revert bad package updates

---

lib/seattleflu/id3c/cli/command/clinical.py

Geocoding expects either NoneType or String objects for address fields,
but NaN values were being sent to the geocoding function. This change
converts any NaNs in the parsed clinical records to empty strings before
geocoding so that the expected data type matches what is passed in.

Convert NaN to Empty String Prior to Geocoding

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

Map newly received value "Surgery admit" to "IMP" (Inpatient) encounter class.

Add new encounter class to mapper

---

lib/seattleflu/id3c/cli/command/clinical.py

When parsing clinical data, several date values are converted to datetime data type which
by default are interpretted as midnight UTC time. Indicating the timezone when these
conversions occur to ensure that date values are converted to midnight local time when a
time component is being added.

Specify timezone when converting date to datetime

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py

In the Y3 HCT project, three instruments are being removed: `testing_determination_internal`, `husky_test_kit_registration`, and `kiosk_registration_4c7f`.  The `husky_test_kit_registration` instrument is being merged into `daily_attestation` form, using the same field names as before. 
Updating the ETL here to remove references to the old instruments and to use `daily_attestation` complete status and the presence of a `barcode_swabsend` value to indicate a dropbox kit.

Update UW reopening ETL to reflect Y3 study design

---

lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

Mapping two newly encountered vaccine values to the appropriate CVX codes in UW retros ETL.

Map new vaccine values to CVX codes

---

lib/seattleflu/id3c/cli/command/clinical.py

Updates to handle `year4` and `year5` manifest formats for SCH. This includes new columns that were added at the end of Year 4 for a fifth covid vaccine dose status, date and  manufacturer.

Updates to SCH ETL to handle changes for Y5 and end of Y4

---

lib/seattleflu/id3c/cli/command/etl/__init__.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py

New vaccine and race values were encountered and are being added to relevant mappings.

Map newly encountered values in UW-retrospectives ETL

---

lib/seattleflu/id3c/cli/command/etl/__init__.py
lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py

Add Kiosk ETL changes to Swab-n-Send ETL branch.

Kiosk ETL revival
