seattleflu/id3c-customizations

- deploy/shipping/views.sql
Update `shipping.reportable_notification_v1` to read the reporting log
from the new 'reporting_log' key in `presence_absence.details`.
Per https://github.com/seattleflu/id3c/pull/47 
Does this need a new sqitch tag?
> Update reportable notifications view

- deploy/warehouse/target/data.sql
- deploy/warehouse/target/data@2019-09-27b.sql
- sqitch.plan
Update the target and organism tables according to the new Thermo Assay
names.
I have a few questions here:
~* How do I know if one of these new pathogens is reportable? ~
~* Should I add anything to the `identifiers` column of `warehouse.organism`? Having seen only the new Thermo Assay names data dictionary, I don't currently understand how that column is populated. I see the comment in the `organism.sql` file of ID3C that says :~
~    >    'Key-value pairs of external identifiers (i.e. dbxrefs) for this organism; keys should use well-known database or ontology prefix (e.g. NCBITaxon)';~
~But don't really know what a dbxref is or where to find it, even after Googling.~
~* Should I track controls (e.g. RnaseP Control)? I can add an extra column to the `with target_lineage (identifier, …
> Link more targets to organisms

- lib/seattleflu/id3c/cli/command/reportable_conditions.py
- schema/deploy/shipping/views@2019-09-30.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2019-09-30.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2019-09-30.sql
This PR depends on https://github.com/seattleflu/id3c/pull/76 and https://github.com/seattleflu/specimen-manifests/pull/7
Update `shipping.reportable_condition_v1` to include `sample_origin` and `swab_site`. These are needed to infer `site` for samples without encounter data from 2019-2020. 
Update `reportable-conditions notify` logic to check `sample_origin` and `swab_site` to determine whether to report to GENERAL or SCH.
> Update reportable conditions

- lib/seattleflu/id3c/cli/command/__init__.py
- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
- lib/seattleflu/id3c/cli/command/etl/longitudinal.py
- lib/seattleflu/id3c/cli/command/longitudinal.py
- mypy.ini
This relies on changes in seattleflu/id3c/pull/88.
Move the clinical, etl clinical, longitudinal, and etl longitudinal commands (and related helper functions) from ID3C to ID3C-customizations.
Make necessary changes to `clinical` and `etl clinical` to ingest new SCH Year 1 data.
> Sch year 1 clinical data

- .travis.yml
- Pipfile
- Pipfile.lock
- lib/seattleflu/id3c/cli/command/etl/__init__.py
- pytest.ini
- tests/docstrings.py
- tests/help.py
- tests/mypy.py
Very similar setup to core ID3C's.  Notably, however, doctests are driven manually by _tests/docstrings.py_ instead of the `--doctest-modules` option since doctest + pytest + namespace packages like _lib/seattleflu/…_ don't get along.
View on Travis: https://travis-ci.com/seattleflu/id3c-customizations
> pytest + Travis

- lib/seattleflu/id3c/cli/command/etl/clinical.py
We were previously converting unknown sex names to 'other' without raising a warning or error. 
Now, raise an Exception if an unknown sex name is provided to the `sex()` mapping function.
> Fix etl clinical sex bug

- lib/seattleflu/id3c/cli/command/etl/clinical.py
This PR reflects changes recently merged into master that make mapping sex and insurance names more strict. 
No longer will unknown names automatically be coded to "other", but rather they will raise an Exception.
This modified clinical ETL with a bump in revision number has been tested with a full run of `etl clinical` on a new clone of the production database.
> Fix sch clinical bug

- lib/seattleflu/id3c/cli/command/clinical.py
In the most recent SCH monthly clinical data pull from 15 Jan 2020, one
of the test result columns changed names. Rename it in the parsing code
to avoid a KeyError.
> clinical parse-sch: Rename test result column

- schema/deploy/warehouse/site/data.sql
- schema/revert/warehouse/site/data.sql
- schema/sqitch.plan
- schema/verify/warehouse/site/data.sql
Adds sites with the types and categories described here: https://docs.google.com/document/d/1SqAlXuZttDXDdrRqdeSS910ecrM737MNRacBXHd6ePg/edit
The only site that is not on here is `Unknown` which I'm not entirely sure what to do with.
Also, `KaiserPermanente` is labeled as `clinic` but we have it as `retrospective`
> Add sites with details

- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
Bumps both kiosk and swab-n-send to REVISION 2 to include updates in response to warning logs in recent etl runs. 
Kiosks:
* Returns `project_id-record_id` if it cannot extract zip code from record. This allows ingestion of participants without a permanent residence and participants who are uncomfortable with sharing their address.
* Include `acute_symptom_onset` as a QuestionnaireResponse item. This was a request from the BBI team.
Swab-n-send:
* Make `collection_date` optional since it is not used by the FHIR etl.
* Do not create Patient Resource if a `patient_id` could not be generated.
* Require Patient and Encounter Resources to be created in order to process a bundle.
> REDCap DET etl updates

- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
Add a new site for Capitol Hill Light Rail Station with spaces so that
the ETL doesn't break.
This is the minimal effort solution to fix the broken Kiosk ETL. The other solution I considered is to strip spaces from site names when comparing them to our `warehouse.site` identifier equivalent. Thoughts?
> etl redcap-det kiosk: Add new site

- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-01-21.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-01-21.sql
- schema/sqitch.plan
- schema/verify/shipping/views.sql
- schema/verify/shipping/views@2020-01-21.sql
Update the `metadata_for_augur_build_v2` to format dates in YYYY-MM-DD format.
Create new view from v2, `metadata_for_augur_build_v3`, that
1. coalesces encounter date with collection date from sample details 
2. uses the new 'category' option from `site.details`.
Addresses two aspects of [this issue](https://github.com/seattleflu/augur-build/issues/32) by reformatting dates and adding an `age_range_coarse` column.
> Update metadata for augur build view

- schema/deploy/warehouse/target/data@2020-01-24.sql
- schema/sqitch.plan
Not linked to any targets yet as we don't know the names Thermo/NWGC
will use.  Marked as reportable to public health, of course!
> Add organism record for 2019-nCoV

- lib/seattleflu/id3c/cli/command/etl/fhir.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
Instead of special casing only zip code and bailing out if other pieces
of information are missing, take a best-effort approach and assume the
record represents a unique participant who hasn't participated
previously and won't participate again in the future.
This is a broadening of the logic we previously used for zip code, and I
think it makes more sense in the bigger picture.  I only realized it
when I was digging into noisy logs, though!  Those same noisy logs are
silenced since missing personal info is now less of an issue with this
more general fallback.
> redcap-det: Fallback to record id-based individual identifier generation

- schema/deploy/warehouse/site/data@2020-01-30.sql
- schema/revert/warehouse/site/data.sql
- schema/revert/warehouse/site/data@2020-01-30.sql
- schema/sqitch.plan
- schema/verify/warehouse/site/data@2020-01-30.sql
Add the Capitol Hill and Westlake light rail stations from the Kiosk ETL
to the warehouse.
Skip `WestlakeCenter` for now, because Izzy said in the #redcap channel
that we likely won't start enrolling participants there anytime soon, if
at all.
> Add new Kiosk sites to warehouse

- lib/seattleflu/id3c/api/datastore.py
- lib/seattleflu/id3c/api/routes.py
- schema/deploy/roles/augur-build-exporter/grants.sql
- schema/deploy/roles/augur-build-exporter/grants@2020-01-31.sql
- schema/revert/roles/augur-build-exporter/grants@2020-01-31.sql
- schema/sqitch.plan
- schema/verify/roles/augur-build-exporter/grants@2020-01-31.sql
~Question here: should I also delete `shipping.metadata_for_augur_build_v2`?~
~My guess is I should not before we deploy https://github.com/seattleflu/website/pull/28 and https://github.com/seattleflu/backoffice/pull/13 which both depend on this PR.~
We decided not to mark v2 as gone until after merging the dependent PRs.
> Update api for new metadata view

- schema/deploy/roles/idle-session-disconnector/create.sql
- schema/deploy/roles/idle-session-disconnector/grants.sql
- schema/revert/roles/idle-session-disconnector/create.sql
- schema/revert/roles/idle-session-disconnector/grants.sql
- schema/sqitch.plan
- schema/verify/roles/idle-session-disconnector/create.sql
- schema/verify/roles/idle-session-disconnector/grants.sql
Create a new database role that has permissions to disconnect database
sessions. This role will eventually be used in a cron job on backoffice
for disconnecting sessions that have been idle for > 30 minutes.
> Add role to perform idle database disconnects

- Pipfile.lock
- lib/seattleflu/id3c/cli/command/__init__.py
- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/longitudinal.py
- locations/Snakefile
- setup.py
Simplifies some of our string column handling and keeps us up-to-date
with latest major version series.
Requires ID3C version 2020.1, which requires Pandas 1.x.
---
Depends on seattleflu/id3c#113.
> Switch to the new true string dtype in Pandas version 1.x

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_clinical_data_pulls.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
- lib/seattleflu/id3c/cli/command/etl/redcap_map.py
Add `etl redcap-det clinical-data-pulls` command. 
I also did some refactoring in `redcap-det kiosks` and `redcap-det swab-n-send` in the process of writing the new etl. 
---
~Still need a couple updates to core ID3C:~ All merged in core ID3C
~- [x] fhir etl: allow sample identifier along with collection identifiers. (see https://github.com/seattleflu/id3c/pull/115)~
~- [x] redcap-det-processor: grant select on `warehouse.sample` (see https://github.com/seattleflu/id3c/pull/114)~
> REDCap DET clinical data pulls ETL

- lib/seattleflu/id3c/cli/command/clinical.py
Allow Excel files in the `clinical parse-sch` CLI tool.
> Accept xls in clinical parse sch

- lib/seattleflu/id3c/cli/command/etl/fhir.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_and_home_flu.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
[Meta.source](https://www.hl7.org/fhir/resource-definitions.html#Meta.source) can be used to document minimal amount of provenance infor for a FHIR Resource.
Adding provenence info to FHIR Bundles will help debugging issues.
The source is currently `{REDCAP_URL}/{PROJECT_ID}/{RECORD_ID}`
> etl redcap-det: add `meta.source` to FHIR Bundle

- docs/CODEOWNERS
A few less clicks on every PR!  Also enables some nice UI affordances on
GitHub.  Docs about CODEOWNERS at:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
> Add a GitHub CODEOWNERS file so reviewers are automatically requested

- dev/detect-rls-leaks
- schema/deploy/policies.sql
- schema/deploy/roles/hcov19-visibility/create.sql
- schema/deploy/shipping/views@2020-03-05b.sql
- schema/revert/policies.sql
- schema/revert/roles/hcov19-visibility/create.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-03-05b.sql
- schema/sqitch.plan
- schema/verify/policies.sql
- schema/verify/roles/hcov19-visibility/create.sql
- schema/verify/shipping/views@2020-03-05b.sql
Details in commit messages.
I tested this locally by doing:
```sh
export PGDATABASE=seattleflu
./dev/detect-rls-leaks  # should show no testable data error
psql -qAt service=seattleflu-restricted -qAt \
<<<"select document::jsonb from receiving.presence_absence order by received" \
| pipenv run id3c receiving upload presence_absence -
LOG_LEVEL=warning pipenv run id3c etl presence-absence --commit
./dev/detect-rls-leaks  # should show red not ok failures
sqitch deploy dev
./dev/detect-rls-leaks  # should show all ok (plus some permission denied warnings)
```
> Row-level security for hCoV-19 results

- lib/seattleflu/id3c/cli/command/clinical.py
When parsing Seattle Children's retrospective data, we convert all
values to strings. Convert the newly appearing 'NA' values (in the
census_tract column) to `None`.
> clinical parse-sch: Convert 'NA' values to None

- lib/seattleflu/id3c/cli/command/reportable_conditions.py
- schema/deploy/warehouse/target/data.sql
- schema/deploy/warehouse/target/data@2020-03-09.sql
- schema/sqitch.plan
Report hCoV-19 in a separate channel and provide a separate metabase url for hCoV-19 specific results.
> Report hCoV-19

- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-03-09.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-03-09.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2020-03-09.sql
Add a new similar to `observation_with_presence_absence_result` specific
to samples tested for hCoV-19.
Currently this view includes all non-control samples, with or without
encounter data, that have been tested for hCoV-19 and all encounters
since March 1, 2020.
> Add hCoV-19 observation w/ presence-absence view

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Additional variables were added to the SCAN REDCap project for `housing_type`:
ltc, Long term care or rehab facility
afh, Adult family home
be, Inpatient or behavioral health residential center
pst, Permanent Supportive or transitional housing center
cf, Correctional facility
I've added ltc, be, pst, cf to our `lodging_options` list but I think afh falls under `residence`.
> etl redcap-det scan-en: add new lodging options

- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/fhir.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Extracts clinical test results, encounter status, encounter class, and discharge disposition from UW Retrospective data. 
Depends on https://github.com/seattleflu/id3c/pull/132. 
Note that, while the DiagnosticReport resources from clinical test result end up in `warehouse.presence_absence`, none of the other variables end up in encounter details. Should we change how our `warehouse.encounter` details document is structured? Should we add new columns to `warehouse.encounter`? Other thoughts?
> Additional uw retro metadata

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Inconclusive results are still skipped because we encode results in FHIR
as a valueBoolean, which must be true or false.  Switching to a
valueCoding first is required for encoding inconclusive results.
> redcap-det uw-retrospectives: Add mappings for additional result codes

- lib/seattleflu/id3c/cli/command/etl/fhir.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- lib/seattleflu/id3c/cli/command/reportable_conditions.py
- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-03-22.sql
- schema/deploy/warehouse/target/data@2020-03-22.sql
- schema/revert/shipping/views@2020-03-22.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2020-03-22.sql
See commit messages for details.
The one thing I'm not sure about is how to filter for only prospective samples. I've currently set that filter as `sample.details -> sample_origin` is either `kiosk` or `mail`. We might add `kp` to that list if Kaiser gets back to us on how their consents are set up (see [slack](https://seattle-flu-study.slack.com/archives/CCAEWSFTK/p1584651186083000?thread_ts=1584567603.073900&cid=CCAEWSFTK))
> hCoV Slack alerts

- schema/deploy/warehouse/target/data.sql
- schema/deploy/warehouse/target/data@2020-03-24b.sql
- schema/sqitch.plan
This includes new Snomed targets from UW retro pulls and the two new COVID targets from NWGC. 
I want to point out that the UW retros include hCoV-19 results. I don't think we want to be including these in our analyses/reporting?
> Link new targets

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Removed 3 instruments from the required instruments list that were only required to get the
sample barcode. 
If a sample has not been received yet, then we only create encounter, patient, questionnaire response for the record. Later on the sample will be created once the record has been updated with `post_collection_data_entry_qc` complete.
(Also, the instrument names have been changed at some point??? 🤷‍♀ )
> Ingest SCAN encounter without sample

- lib/seattleflu/id3c/cli/command/etl/fhir.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
If a sample arrives in a condition that is unable to be tested, it will
be marked never_tested at unboxing.
If later during lab testing/processing it falls into the never_tested
category (such as a PCR fails), the REDCap record will be updated w/
"no" for the able_to_test variable.
> etl redcap-det scan: Ingest 'able_to_test'

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
This was a new field added to make the shipping process easier.
We need to ingest it to create the correct hashed address identifier.
I've tested locally and the canonicalized address returned by SmartyStreets __does__ include
the apartment number.
> Include `apartment_number` field in address

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
We've run into records where the sample collection barcode from
different fields don't match. This will alert us if this happens
again and prevent ingestion of the wrong barcode.
> etl redcap-det scan: add assertions to check barcodes match

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
When we were only including Specimen.note for `no` answers, this prevented updates for when it gets changed from `no` to `yes` (since we concatenate `sample.details`)
Noticed this because currently we have more `never-tested` samples within `warehouse.sample` than records marked `able_to_test: no` in REDCap.
> etl redcap-det scan-en: include Specimen.note for `yes`/`can-test`

- lib/seattleflu/id3c/cli/command/etl/fhir.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- setup.py
Adds the following commands:
```
id3c etl redcap-det scan-es
id3c etl redcap-det scan-vi
id3c etl redcap-det scan-zh-Hans
```
Details in the commit messages. Requires https://github.com/seattleflu/id3c/pull/147.
~I've not yet fully tested this locally on a fresh copy of the database, but that's in progress. However, type checks and our (minimal) tests pass and it works as expected on an older database copy.~ Tested locally and seems good to me. Travis checks are failing because I haven't yet released the core ID3C change.
> REDCap DET: Support multiple SCAN projects, one per language

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Add traditional Chinese (zh-Hant) to the list of REDCap SCAN projects to
ingest.
> etl redcap-det scan: Add zh-Hant to project list

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Add Somali (so), Korean, (ko), and Russian (ru) REDCap SCAN projects to
the list of projects we're ingesting into ID3C.
> etl redcap-det scan: Add so, ko, ru projects

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Add Tagalog, Amharic, and Tigrinya to the list of REDCap SCAN projects
to ingest.
> etl redcap-det scan: Add tl, am, ti to projects

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
The coded value for zipcodes in REDCap are arbitrary numbers instead of
the actual zipcode. This is due to branching logic causing problems
when the code is the actual zipcode. Add `zipcode_map` to convert these
codes to the real zipcode.
> etl redcap-det scan: Add `zipcode_map`

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Refactor redcap-det scan command to support multiple types of SCAN projects:
Each project is registered as `id3c etl redcap-det scan-$TYPE-$LANG`
command if `$TYPE` is provided. To minimize change in command calls, the
default SCAN commands for initial REDCap projects remain the same.
The new ETL added for the SCAN research project will be `id3c etl redcap-det scan-irb-en`
> Add SCAN-IRB EN REDCap project

- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-05-13.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-05-13.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2020-05-13.sql
The addition of the materialized view made the view dependencies more complicated, so I reorganized the view definition file to drop all views at the very top. This required the view definitions to be re-ordered and created in the order of dependency as well. Since I had to re-order them, I also organized them into broad categories to hopefully make them easier to understand. (Sorry the file diffs are a little crazy because of this...)
And of course, the actual point of this PR was to add a date cutoff to the SCAN return results view so that we only return results to participants in the SCAN _research_ study.
> Add date cutoff to SCAN results

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
The study only wants us to ingest "true" enrollments where a participant
was mailed a swab kit. "True" enrollments can be identified by the
participant completing the illness_questionnaire. However, there is
a bug in REDCap that sometimes leaves the instrument marked as
incomplete/unverified. To get around this, we are checking that the
`illness_q_date` is filled in to verify that the instrument is complete.
However, there is yet another bug in REDCap that sometimes leaves the
`illness_q_date` blank. To catch these records, we are also checking
that the back_end_mail_scans instrument is complete.
This leaves us with a majority of records being ingested the day of
enrollment due to the completion of the `illness_q_date` and some
straggling records ingested the day after enrollment where …
> etl redcap-det scan: skip "false" enrollments

- lib/seattleflu/id3c/api/routes.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- schema/deploy/roles/scan-dashboard-exporter/create.sql
- schema/deploy/roles/scan-dashboard-exporter/grants.sql
- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-06-15.sql
- schema/revert/roles/scan-dashboard-exporter/create.sql
- schema/revert/roles/scan-dashboard-exporter/grants.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-06-15.sql
- schema/sqitch.plan
- schema/verify/roles/scan-dashboard-exporter/create.sql
- schema/verify/roles/scan-dashboard-exporter/grants.sql
- schema/verify/shipping/views.sql
- schema/verify/shipping/views@2020-06-15.sql
Changes to set up the views for the public Power BI dashboard:
1. Ingest `illness_q_date` field from REDCap - this represents the "completed enrollment" date
2. Add a `power-bi-exporter` role to the database.
3. Add new views for the dashboard:
- shipping.scan_demographics_v1
- shipping.scan_hcov19_positives_v1
- shipping.seattle_neighborhood_districts_v1
- shipping.scan_enrollments_v1
> Views for Power BI Dashboard

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- schema/deploy/warehouse/site/data.sql
- schema/deploy/warehouse/site/data@2020-07-13.sql
- schema/revert/warehouse/site/data@2020-07-13.sql
- schema/sqitch.plan
- schema/verify/warehouse/site/data@2020-07-13.sql
Includes updates to the ingest to use the get() method for fields that
do not exist in the new project.
> etl redcap-det scan: Add SCAN kiosk project

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Depends on https://github.com/seattleflu/id3c/pull/159
This should fix all of the extra "Could not create Specimen Resource due to lack of barcode." warnings we've been receiving from the mail-in project.
See commit messages for more info.
> Update is_complete checks

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Add a new discharge disposition mapping to the REDCap DET ETL for UW
retrospective data. We received a value of "still a patient", for a
patient that was not actually discharged. We will map this value to
None as there is no matching FHIR code.
> etl redcap-det uw-retros: add discharge mapping for 'still a patient'

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Add a new discharge disposition mapping to the REDCap DET ETL for UW
retrospective data. We received a value of "deceased - o: deceased -
organ donor", and will map this to an appropriate FHIR code.
> etl redcap-det uw-retros: add discharge mapping for organ donor

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Before this change, an unmapped discharge disposition value would stop
the ETL process. With this change, we skip the problematic record and
continue processing.
> Skip record with unmapped discharge value

- lib/seattleflu/id3c/api/routes.py
- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-08-19.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-08-19.sql
- schema/sqitch.plan
- schema/verify/shipping/views.sql
- schema/verify/shipping/views@2020-08-19.sql
- Change `shipping.scan_encounters_v1` to a materialized view in order to speed up downstream queries
- Add `shipping.scan_demographics_v2`
- Add `shipping.scan_redcap_enrollments_v1`
Will add a new cronjob to backoffice to refresh the `shipping.scan_encounters_v1` view every 5 minutes. See https://github.com/seattleflu/backoffice/pull/73
> Formative v2 API + internal dashboard API

- lib/seattleflu/id3c/cli/command/etl/redcap_det_asymptomatic_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_and_home_flu.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_map.py
Currently in ID3C, a `null` symptoms response captures both encounters
with asymptomatic participants as well as participants who did not fill
out the Illness Questionnaire. Instead of relying on a proxy field
like `illness_questionnaire_complete` or `illness_q_date` to determine
if a `null` symptoms response is indicative of an asymptomatic
participant or simply indicates missing data, create a new code to
distinguish the condition where a participant reports having no
symptoms.
> etl: Create distinct code for having no symptoms

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Add check for `nasal_swab_collection` is complete because the new
SCAN Husky Test project does not have the `illness_questionnaire`
instrument nor the `back_end_mail_scans` instrument.
> etl redcap-det scan: Add `nasal_swab_collection` to complete check

- lib/seattleflu/id3c/cli/command/etl/redcap.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Normalize netids and add @washington.edu domain before hashing for patient_id.
The netids coming from redcap sometimes have @uw.edu, and sometimes no suffix.
Normalizing helps standardize and also reduces potential future conflicts if we
hash other usernames.
> etl redcap-det scan: normalize SCAN husky netids

- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
This is the REDCap DET ETL for the UW reopening project. For this, I copied the code from redcap-det_scan. We should clean this up in the future by moving the code into a shared module, but for now it's a copy in here.
It's very likely that this code will have to be updated next week as REDCap fields change, but this is a working starting point.
There are many questionnaires in here!
> Add ETL for UW reopening project

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Add a new site for PICA-WA to the SCAN In-Person Enrollments project.
> etl redcap-det scan: Add PICAWA site

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
If a given `core_birthdate` is invalid (e.g. year is 0000), return the
birth date as None and emit a warning.
> etl redcap-det uw-reopening: Handle invalid birth date

- Pipfile
- Pipfile.lock
- setup.py
The core id3c package is technically required for id3c-customizations,
but the editable install of id3c through pipenv does not resolve this
dependency. 
Remove id3c from setup.py so that we can update Pipfile.lock with the latest core id3c dependencies.
> setup.py: Remove id3c as a requirement

- lib/seattleflu/id3c/cli/command/etl/fhir.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_asymptomatic_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_and_home_flu.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
~Add Encounter.meta.source to track the provenance information of the
encounter. For the REDCap DET ETLs, this is a URL with the format:~
```
https://redcap.iths.org/<project_id>/<record_id>/<event_name>/<repeat_instance>
```
~Event name and repeat instance number are only included if the
project has repeating events.~
See latest commits for details
Should be deployed along with https://github.com/seattleflu/id3c/pull/170
> Encounter Provenance

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
Convert `testing_trigger` to a boolean, and stop ingesting the free text field `surge_selected`.
Depends on the `surge_selected_flag` to be in the production REDCap.
> Testing trigger

- lib/seattleflu/id3c/cli/command/etl/redcap.py
When building questionnaire items, don't add additional_items to the
items list if they are None.
> redcap.py: Skip additional_items that are None

- schema/deploy/shipping/views.sql
- schema/revert/shipping/views.sql
- schema/sqitch.plan
In recent projects we started capturing questionnaire items as the
valueDecimal FHIR value type. Today, we're capturing `bmi` as valueDecimal.
We need to expose these in the shipping.fhir_questionnaire_responses_v1
view.
In python we capture these as `float`. In the shipping view we expose them
as the postgres `double precision` type. This type allows for 15 digits
of precision. We probably don't need that much precision for `bmi` but we
may for other items that get stored as valueDecimal.
** I'll create the sqitch tag just before deploying.
> Add valueDecimal support to a shipping view

- lib/seattleflu/id3c/cli/command/etl/redcap.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
Generalize non-finite float handling and remove special-casing. Details in commits.
> etl redcap-det: Ignore float values which are non-finite (NaN and ±Inf)

- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
The unscheduled event has fewer instruments than a regular
scheduled encounter event but is similar enough that this ETL job can
treat it just like a scheduled encounter event.
> Accommodate unscheduled event in childcare ETL

- lib/seattleflu/id3c/cli/command/offer_uw_testing.py
We expect the job to run all the time, but we will purposefully not
configure quotas for hours outside "waking" hours as not to annoy
participants with alerts from REDCap. This change lowers the log
level from WARNING to INFO for two cases when the job doesn't find
a quota to work with.
> Lower log level when no quota exists for uw offers

- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-12-01.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-12-01.sql
- schema/sqitch.plan
- schema/verify/shipping/views.sql
- schema/verify/shipping/views@2020-12-01.sql
Create a new version of the incidence modeling view and observation with presence absence modeling view.
Also refactor many of our existing hCoV-19 presence-absence CTE queries into a new view for reduced duplication across our view definitions.
~I'm waiting on one confirmation from Roy as to whether he wants all samples _and_ all encounters in these new views, or just all samples.~
> Create new versions of our modeling views

- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2020-12-23.sql
- schema/revert/shipping/views@2020-12-23.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2020-12-23.sql
To speed up the __uw_priority_queue_v1 view, materialize UW encounters.
Here are times running against the production DB:
__uw_priority_queue_v1 as it is in Master: 53 secs 501 msec
__uw_priority_queue_v1 as it is in this commit: 2 secs 363 msec
refresh the __uw_encounters materialized view: 19 secs 863 msec
For testing, I diff'ed sorted output from the master version of
__uw_priority_queue_v1 to that of the new version of the view. The
output was the same.
This needs a corresponding Backoffice change to create the cron job
to refresh the materialized view. That is seattleflu/backoffice#112
> Materialize UW Reopening encounter view

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
This PR:
1. Brings in new fields added to the enrollment questionnaire.
2. Removes asserts/LOG.error (replaces the meaningful ones with LOG.warning) so that the job doesn't stop when we see an odd record.
I'm not bumping the revision # on this one. I'll do that after Jessica sets values for the new fields.
> UW Reopening ETL changes for Winter

- lib/seattleflu/id3c/cli/command/etl/redcap.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
Favor REDCap survey timestamps over custom date fields when available when determining the encounter date or the sample collection date.
For sample collection date, do not use a value that the participants writes on the tube if that value is in the future.
I did not bump the ETL revision number in this PR. We're going to need to process all DETs soon once some new REDCap calculations get backfilled.
> Uw reopening system dates

- schema/deploy/shipping/views@2020-12-30.sql
- schema/revert/shipping/views.sql
- schema/revert/shipping/views@2020-12-30.sql
- schema/revert/templates/deploy/pg.tmpl
- schema/revert/templates/revert/pg.tmpl
- schema/revert/templates/verify/pg.tmpl
- schema/sqitch.plan
- schema/verify/shipping/views@2020-12-30.sql
There is shockingly no view of hcov19 results with all three barcodes
plus a result date. Create a view of this as a source of truth when
creating linelist exports for the Washington Dept. of Health.
-----------------------
See https://github.com/seattleflu/backoffice/pull/115 for usage.
> views: Create new view for WA DoH linelists

- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
Never used, noticed while I'm auditing all usages of REDCAP_API_TOKEN in
order to retire it.
> Remove never-used ETL data class property referencing REDCAP_API_TOKEN

- lib/seattleflu/id3c/cli/command/offer_uw_testing.py
Use the datetime so we have more info to track which job run
updated which records.
> Use datetime instead of date when setting `testing_date`

- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
Add the new 2021 Childcare Redcap project into the childcare ETL.
Includes addition of new sites added in the new project.
Note: Redcap project 31118 can be used for testing this out with test records, because the real 2021 childcare redcap project is already in production with real records.
> redcap-det-childcare etl: include 2021 Childcare Project data

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
The UW reopening (HCT) project now includes an event for each month. This
event contains only a monthly survey. We don't ingest that
survey, so it makes sense to skip the record instance that this event
is in. Rather than log a warning, now log info when we see an event
that is not `enrollment` or `encounter`.
> Don't warn for unexpected event names for UW-reopening

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
Move the logic for age ceiling to within the `cast_to_integer` function
of `questionnaire_item`. This prevents age from being returned as `None`
due to 0 being a falsy value.
This also consolidates the type casting of responses into a single
function for easiers future debugging.
> etl redcap-det scan: move age ceiling logic to fix `None` age values

- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
The 2021 Childcare project doesn't have the `illness_q_date` variable like
the pilot version ("Childcare") does. Both projects have this info
collected on a "Symptom Check" survey, so both have
`symptom_check_timestamp' available, so we can use that variable.
The revision is bumped so that we will have this collected consistently
across the two studies.
With this change made locally, the ETL successfully processed all the waiting DETs in the queue.
> Childcare ETL: replace 'illness_q_date'

- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
When using a REDCap server generated survey timestamp, we should do so
by using the `extract_date_from_survey_timestamp` function instead
of accessing the timestmap variable directly. If the survey has not
been completed, a value of `[not completed]` will be returned for
the timestamp. The function handles this correctly.
After this is merged, generate a DET for the 2021 Childcare project record 178.
For example:
REDCAP_API_URL="https://redcap.iths.org/api/" envdir /home/jccraft/gitroot/backoffice/id3c-production/env.d/redcap id3c redcap-det generate --project-id=29351 "178" > /home/jccraft/jccraft_temp/det_work/det.ndjson
> Childcare ETL: Use survey timestamp correctly

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
For the UW Reopening ETL, when computing the encounter date for the
follow up encounter, use the survey timestamp if it exists then fall
back to the timestamp variable. We had a case where the ETL failed
because the timestamp variable had not been populated.
> Prefer survey timestamp for UW reopening follow up

- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
In the Childcare ETL I fixed how we use the `symptom_check_timestamp` for the
collection_date, but I missed the second place where we use it. This
commit calls `extract_date_from_survey_timestamp` to use the
`symptom_check_timestamp` for the questionnaire item.
After this is merged, generate a DET for the 2021 Childcare project record 178.
For example:
REDCAP_API_URL="https://redcap.iths.org/api/" envdir /home/jccraft/gitroot/backoffice/id3c-production/env.d/redcap id3c redcap-det generate --project-id=29351 "178" > /home/jccraft/jccraft_temp/det_work/det.ndjson
> Use the symptom_check_timestamp the right way

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
The UW Reopening ETL's data quality check needs to accommodate records
that didn't have their UW Housing Group variables set when the REDCap
calculations were implemented. If the value is '' consider it 0 for the
housing group count.
> Accommodate unset UW housing group variables

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
For the UW-reopening ETL, by pulling the `testing_date` from the
testing_determination_internal form we will be able to give a more accurate
analysis of how much time passes between invitations for a given
participant.
The revision number is not incremented in this commit because all
records will be pulled manually.
I removed a sentence from the code comment that was not accurate.
> Pull `testing_date` from the testing_determination_internal form

- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
SCH retrospective metadata includes new values for sex, race,
and hispanic_latino fields.
> etl clinical: Add latest SCH values to value maps

- lib/seattleflu/id3c/cli/command/reportable_conditions.py
Send reportable conditions notifications for Yakima schools home and
observed results to the slack channel ncov-reporting-schools in
addition to the standard ncov-reporting. The schools channel is also
used by the Snohomish schools study.
> reportable_conditions: send Yakima notifications to schools channel

- schema/deploy/roles/idle-session-disconnector/grants.sql
- schema/deploy/roles/idle-session-disconnector/grants@2021-04-22.sql
- schema/revert/roles/idle-session-disconnector/grants.sql
- schema/revert/roles/idle-session-disconnector/grants@2021-04-22.sql
- schema/sqitch.plan
- schema/verify/roles/idle-session-disconnector/grants@2021-04-22.sql
These details will let our connection watchdog processes (e.g. for slow
queries) be more selective in what they terminate without revealing the
full query of every connection to non-superusers.
The format of this comment (or "remark" in Metabase's parlance) is
reasonably guessable, but I also checked the code.¹  If the format
changes in the future and the parse fails, the new "metabase" column
added here will just be null.  This seems like a reasonable failure
mode.
¹ https://github.com/metabase/metabase/blob/f76d8333/src/metabase/query_processor/util.clj#L26-L37
--- 
See also https://github.com/seattleflu/backoffice/pull/160#issuecomment-848177312.
> Extract Metabase details for each connection from the query comment 

- Pipfile.lock
- mypy.ini
- setup.py
After prior deployment that updated click to version 8.0.1, ETLs started
encountering issues. They continued to run without error, but changes were
rolled back inexplicably. This is possibly related to change in click
flag_value typing [#1886](https://github.com/pallets/click/issues/1886).
Confirmed with local testing that rolling back to version 7.1.2 resolved
the problem. Pinning click to 7.x while investigating further and making
required code changes to upgrade to 8.x.
> Pinning click to version 7.x

- tests/sqitch-plan.py
Tags are how Sqitch enables reworking of changes (such as our
shipping/views change) and are intended to mark the point when a schema
is "released" and thus existing change scripts can't be edited in place;
instead adding a new change or rework is necessary.
In our case, we "release" our schema when we deploy it to production,
and we typically deploy to production on every merge to master.  This
means we very rarely have periods where a tag isn't necessary, so
require one via our CI tests.
> Tests: Check that on master the Sqitch plan always ends with a tag

- lib/seattleflu/id3c/cli/command/etl/redcap.py
We've recently started seeing redcap records with survey instruments that
have a status of complete, but the automated timestamp value is the string
['not complete'] instead of an actual timestamp.
When looking for survey timestamps, we can consider that 'not complete'
value to mean the survey is indeed not complete, and return no extracted
timestamp, instead of throwing an error.
> etl redcap: ignore 'not complete' survey timestamps

- lib/seattleflu/id3c/cli/command/reportable_conditions.py
With use of accessioning API, provenance data no longer contains a
`workbook` value. Updating function to avoid exception when workbook
value is null in shipping view.
> Handle missing provenance workbook value in Slack post function

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
When creating encounters in the uw reopening ETL, consider kit
registration barcode when trying to create the specimen.
There has been a change in the testing workflow, such that some
samples will be unobserved testing (not kiosk, but also not
swab and send), and they won't have a PCDEQC filled out.
For these records, the way to link the redcap encounter to
the sample is to use the kit registration barcode field,
called barcode_swabsend.
> etl uw-reopening: Include kit registration barcodes

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
Many PTs are marking kit registration form as complete without filling out required
fields including barcode. To prevent this from creating excessive number of alerts,
additional check is being added to make sure barcode value is present before attempting
to create specimen entry for FHIR bundle.
> Add check for barcode on HCT kit registration for dropbox samples

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
The UW retrospectives ETL is pulling data from an EMR that doesn't
conform to the FHIR specification for encounter class, available at
https://www.hl7.org/fhir/v3/ActEncounterCode/vs.html.
In order to fix this, we set up a table that maps the EMR's values
to FHIR values, but it's missing several of the EMR's values, causing
"Unknown encounter class" exceptions. Add them so the code stops
barfing when it um, encounters one.
> Fix encounter class mapper

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Since non-alphanumeric characters are being removed in the previous line, removing
comma from this string comparison.
> Remove comma from reorder string check

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
Remove filter on migrated enrollments to allow those records and instruments to be ingested from the new HCT REDCap project. This filter was originally implemented when issues were identified with the data migration of records from the old REDCap project to the new one. Now that data cleanup and QC has occurred, this filter can be safely removed.
Also removing fields no longer being used in REDCap from the ETL process. These fields accounted for some of the differences between enrollment records in the old and new projects. Those REDCap fields that are being removed will subsequently be dropped from existing HCT records in ID3C as well as any shipping views that reference them.
> ETL: REDCap DET - HCT process migrated enrollments and drop unused fields

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
Adding a check to determine if a barcode is valid before creating a
specimen entry in the FHIR bundle. This will prevent downstream warnings
in the FHIR ETL when an invalid barcode is encountered.
This is being implemented on UW reopening only for now due to the higher number
of invalid barcodes received and QC process transferring to LIMS.
> Check barcode before including specimen entry in FHIR bundle

- lib/seattleflu/id3c/cli/command/clinical.py
Regex pattern on the collapse_columns function was incorrectly
defined allowing the last character of the `stub` parameter to be
optional. This had the effect of unintentionally collapsing `census_tract`
column when trying to collapse `race` columns because both contain `rac`.
The updated pattern requires all characters of the `stub` parameter to
be present in the column name.
> Update regex on clinical parse collapse_columns function

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Add UnknownTestResult exception a la UnknownSampleOrigin/UnknownHospitalDischargeDisposition to gracefully handle bad test result values without dying from the uncaught Exception.
Prior logic said that if a test result isn't one of a very narrow set of values (e.g. 'detected', 'positive', 'negative', 'not detected'), just skip it. This will do the same thing, for all values that are not one we can confidently map to True or False.
> Handle unknown test results more gracefully

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
Update parsing for SCH clinical data files to include ICD-10 codes. The
codes are stored in a series of 10-12 new columns in the workbooks and are
converted to an array to be included in JSON output.
> Update parsing and ETL for SCH clinical data files.

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
When the get_geocoded_address() function from the geocode class returns
None, update the 'bad_address' field in redcap to yes. This can be used
to trigger a notification to the participant and or PC team for rapid
resolution.
> Notify REDCap of bad addresses

- Pipfile.lock
- lib/seattleflu/id3c/cli/command/etl/fhir.py
- setup.py
We started receiving an incompatible type error when we upgraded `mypy` previously,
so it was pinned to 0.910. The error was caused by `mypy` not being able to
determine the correct type for an optional nested dict that is part of a larger
dictionary being returned from a function. Initializing this key/value as an
empty dictionary prevents the incompatible type error in `mypy`.
> Minor change to fhir ETL to unpin mypy

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
While testing the ETL today, we came across new values in the `covid_vaccine` field that needed to be mapped to corresponding CVX/FHIR coding. We found that "purple cap" and "gray cap" are both for Pfizer for 12 and older, and "orange cap" is for ages 5-11 (https://www.fda.gov/media/153714/download). The CVX code and description for Novavax vaccine was found here: https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html
> add additional vaccine codes

- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_reopening.py
The `is_complete` function will return `None` if the given instrument
does not exist. Updating in two ETLs where it was comparing the result to
`False` so that it will also handle `None` result appropriately.
> Handle missing REDCap instrument when checking completeness

- .gitignore
Ignore CSV, NDJSON, XLS, and XLSX files when pushing to this repo. There are
currently two such files in the `locations/data` directory, neither of which
has ever been updated since it was initially pushed. If these files do need to
be updated in the future they can be explicitly excluded in `.gitignore` or
forcefully added and pushed.
> Update gitignore to ignore data files

- Pipfile
- Pipfile.lock
- mypy.ini
- setup.py
Fixes required to get id3c-customizations working on Python 3.9. Don't merge this or everything will burn to the ground.
> Python 3.9 fixes

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
The fields, `admit_during_this_encounter` and `admit_to_icu` from Seattle Children's are added for ingestion. These fields gets parsed and ingested, then stored under `details` -> `responses` in the warehouse.encounter table as either `yes` or `no` responses.
Additionally,financial aid and self-pay values were added to the Insurance mapping.
Testing Data Used:
1. SFS_Year1_Main_Data_20210922
2. SFS_Year2_Main_Data_20210923
3. SFS_Year3_Main_Data_20211207
4. SFS_Year4_Main_Data_20220124
5. SFS_Year4_Main_Data_20220208
6. SFS_Year4_Main_Data_20220209
Testing Done Include for All 6 Test Data Under Local:
1. id3c clinical parse-sch
2. id3c clinical upload
3. id3c etl clinical
Testing went well where the fields showed up as expected and the new insurance values were parsed. Y1, Y2, Y3, and Y4 …
> SCH Retro Additional Field Ingestion

- lib/seattleflu/id3c/cli/command/etl/clinical.py
A new value was encountered in a recent batch of clinical data for non-binary
sex. Adding to map so that this value can be standardized.
> Update mapping for clincial ETL to include new sex value

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/redcap_map.py
Adds functionality to parse PHSKC clinical data from excel files and join that clinical
data with lab manifest data. Outputs parsed and joined data to stdout in ndjson format.
Parsing of the data involves generating an individual and encounter identifier, calculating
a patients age, and geocoding their address. Once parsed and columns of interest are
selected, this data is joined with sample data from aliquoting sheets provided by the lab.
Samples are joined using `main_cid`, `all_cids`, and `barcode` (with priority given in that
order). Any records that do not have an associated sample are dropped before being output.
Because CIDs are meant to link samples to phskc records, any duplicate CIDs in the lab
manifest are dropped before joining the data.
Note this parsing depends on a parsed …
> Parse PHSKC Clinical Data

- lib/seattleflu/id3c/cli/command/clinical.py
Add a stubbed version of clinical parse-phksc command to
be used by backoffice upload-phskc-retrospective-data-pulls.
> clinical: add stub of parse-phskc

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Multiple new test result values were encountered during ingestion of UW Retros metadata
that begin with "invalid", which had not been previously seen or mapped. Adding to the
`test_result_prefix_map` to re-process those records that failed and handle these values going forward.
> Adding new value to test result mapping function

- lib/seattleflu/id3c/cli/command/etl/clinical.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Updates to clinical ETL for processing of PHSKC data. This data has being parsed and pre-processing
from Excel worksheets, and inserted into the clinical receiving table. This update to the clinical
ETL will transform the data into FHIR bundle format and inserted into the fhir receiving table to be
processed by the FHIR ETL.
This was modeled after the UW Retrospectives process, which is currently the only clinical data ETL that
uses the FHIR format. To expediate the development and avoid duplicating code, it utilizes existing
functions that were originally designed for REDCap ETLs wherever possible.
> Modify clinical ETL to process PHSKC data into FHIR bundles

- lib/seattleflu/id3c/cli/command/offer_uw_testing.py
We are seeing 1-2x/daily failures of this job due to timeouts
on the call to redcap to update records. As the project has grown
larger and there have been performance issues in the redcap service,
let's try dialing this threshold down to update only 150 records in
a batch to see if it improves the reliability.
> offer_uw_testing: dial down redcap batch size

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
To reflect data model changes upstream, include new values:
encounter_status:
no show
encounter_class:
series pt-ot-st
deceased - organ donor
hospital outpatient surgery
observation
There was some ambiguity in how to map "deceased-organ donor"
as an encounter class (we do already handle it as a discharge
disposition), but we've decided to default to mapping it to an
ambulatory/outpatient encounter because that's generally our
default and there wasn't an unknown option.
> uw retro etl: map new encounter_status and encounter_class values

- lib/seattleflu/id3c/api/datastore.py
- lib/seattleflu/id3c/api/routes.py
Adding an API endpoint to retrieve records from the deliverables log table, for use
by LIMS for QC processes.
Since entries in this table only include sample _OR_ collection barcode (depending on the
process being logged) and LIMS does not have a record of the sample identifiers assigned
to tiny swabs, this endpoint will return the associated sample and collection barcodes for
each log entry. The `details` returned for each record are limited to values that may be useful
for QC.
Access to this endpoint and `shipping/latest-restults` are being limited to localhost and LIMS IP
address which are the only current use cases.
> Deliverables log API endpoint

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
- lib/seattleflu/id3c/cli/command/etl/fhir.py
This change allows the PHSKC ingestion pipeline to also ingest the `result_value` and `collect_ts` fields from the PHSKC data into the `presence_absence` table in ID3C.
Functionality was added that adds these fields to the fields that we extract from provided PHSKC sample metadata and parses it into ndjson files. Additionally, this change adds functions that generate FHIR compatible Observations and Diagnostic report resources which can be ingested into ID3C.
> Ingest result_value field for PHSKC samples

- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_asymptomatic_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_childcare.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_and_home_flu.py
Data collection has ended for these studies. Removing from init
will disable the associated `id3c etl redcap-det ...` commands.
We are leaving the command for the various ETLs as a record of
how the data from these studies was historically processed.
> Deprecate ETLs for ended studies

- lib/seattleflu/id3c/cli/command/clinical.py
PHSKC data is uploaded to Sharepoint prior to the lab adding it to AQ sheets. When this data is parsed the outputted files are non-empty since they have a newline character, making it more difficult to verify if a file is truly non-empty. This change only outputs PHSKC data when the DF is non-empty, ensuring the file is empty if there is no aliquot data to join to and making it simpler to check files downstream for emptiness.
> Only Dump PHSKC NDJSON if Data Exists

- .gitignore
- MANIFEST.in
- lib/seattleflu/id3c/.gitignore
- lib/seattleflu/id3c/api/routes.py
- lib/seattleflu/id3c/api/static/documentation.html
Add documentation for the API endpoints in the id3c customizations
package. Surface these via /v1/documentation/customizations
Documentation created using comments in from routes.py
Add a manifest to include the documentation static file. When this
and id3c get loaded together, only the static files from id3c will
get picked up automatically by setup tools.
---------------
For local testing, you can start the API with:
`pipenv run python -m id3c.api FLASK_DEBUG=1`
and then visit http://127.0.0.1:5000/v1/documentation/customizations 
(updating that port if necessary locally)
You can also see how the files get packaged and what is included using:
`pipenv run python setup.py sdist`
> Document customizations API endpoints

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Also make error messages more informative when we get an unknown
encounter class/status so it's easier to track down where they're
coming from.
> Add new encounter class mapping

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
A new value was received in UW Retros project with a slight variation from a
previously mapped value ("years" vs. "yrs"). Adding the new value to the map.
> Add value to vaccine map

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
A large batch of records were updated with new vaccine values which were not mapped
yet. It looks like the nomenclature changed slightly in EPIC and got pushed to REDCap. All
values were previously mapped with a different name.
> Add new values to UW Retros ETL vaccine mapper

- lib/seattleflu/id3c/cli/command/clinical.py
The `encountered` and `birth_date` values were recently updated to be timezone-aware, so the age
calculation should use those two values rather than `birth_date` and `collect_ts` (which is timezone-naive).
> Use timezone aware encountered value for age calc in PHSKC parsing

- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2022-06-24.sql
- schema/revert/shipping/views@2022-06-24.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2022-06-24.sql
This change adds the encounter date to the PHSKC shipping view for use in downstream
analysis.
> Add Encounter Date to PHSKC Shipping View

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Mapping a new value for Sinovac vaccine in the UW Retros ETL.
Also reworked the mapping to use two dictionaries to eliminate duplicate entries.
> UW-retros ETL add sinovac vaccine and rework mapping

- lib/seattleflu/id3c/cli/command/clinical.py
Previously the `encode_addresses` function attempted to directly access the location identifier, however this location has the potential of being a null value. We should first make sure the location exists before accessing its identifier.
Although I'm not sure if this fixes the root cause of the PHSKC parsing failure from 7/29, I think it is still an improvement to the code logic.
> Check Existence of Location Before Accessing its Identifier

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
A new coding was added for a novavax vaccine, which
can be mapped to CVX 211.
> Add novavax vaccine for uw retros

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
We recently filled in some missing date in a handful of UW Retros records in REDCap, but some date fields were populated with a non ISO date format (MM/DD/YYYY) which causes issues with downstream fhir processes. This change adds a conditional that reformats this date string into ISO format for compatibility with downstream processes.
> Handle New Vaccine Date Format in UW Retros

- Pipfile.lock
- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
There are new variables in the data for Seattle
Childrens retros for covid vaccine dose 4
(covid_vx_d4, cov_d4_date and covid_vx_manu4)
These still have the Year4 prefix, which means we have two formats (with and without these new variables) under the same year4 format. Additional tweaks are made to accomodate year4 files both with and without these new variables.
> Process SCH covid dose 4 data

- lib/seattleflu/id3c/cli/command/etl/redcap.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_fh_airs.py
- lib/seattleflu/id3c/cli/command/etl/redcap_map.py
Rework of AIRS ETL based on a full review of the REDCap project design and discussions with the Study Team.
These changes include:
- mapping integer values to strings where needed
- correctly associating REDCap instruments with encounter type (weekly instrument as initial encounter; symptoms instrument as follow-up encounter)
- correctly processing two sets of swab kit instruments to associate each sample with encounter which triggered the kit
- mapping race to match standard ID3C coding
- ingesting detailed symptoms as Questionnaire Responses
- generalizing detailed symptoms to standard ID3C coding and ingesting as Conditions
- correctly ingesting vaccination responses from enrollment and weekly instruments
- bumped revision number
> AIRS ETL updates

- lib/seattleflu/id3c/cli/command/etl/redcap_det_fh_airs.py
Minor changes based on QC of records after #338 was deployed.  Updated logic to check for completed PCDEQC _or_ swab results to determine if sample was received. Changed order of prioritized barcodes to use value from BEMS instrument (which is always required).
> AIRS ETL updates 2

- lib/seattleflu/id3c/cli/command/etl/clinical_retrospectives.py
The UW Retros ETL got back on track on 2022.10.26, and since then over 1000 records were updated in the progress. In the updates, a new encounter class (`freestanding`) was added. This change adds that class to the encounter mapper, mapping it to IMP since it seemed the most appropriate.
Tested by generating DETs for records updated in the retros project after 10-25. Freestanding was the only new value I found after running through those DETs.
> Add New `Freestanding` Encounter Class to UW Retros Encounter Map

- lib/seattleflu/id3c/cli/command/etl/longitudinal.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_scan.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
Marking deprecated ETLs for projects that have ended and cron jobs disabled.
> Mark deprecated ETL modules

- lib/seattleflu/id3c/cli/command/etl/__init__.py
Work is ongoing to clean up some of the SQL scripts supplying us with UW retro data. Along with that work, some race and ethnicity mappings have been updated and/or changed. This commit adds these new mappings.
> Add New Race and Ethnicity Mappings for UW Retro Records

- README.md
- lib/seattleflu/id3c/api/routes.py
- schema/deploy/shipping/views.sql
- schema/deploy/shipping/views@2022-12-02.sql
- schema/revert/shipping/views@2022-12-02.sql
- schema/sqitch.plan
- schema/verify/shipping/views@2022-12-02.sql
This change adds a shipping view for HCT dashboard data pulls, essentially a simplified version of the hct encounters v1 view but with less data and simplified joins. This shortens query time and provides only the necessary data for quicker lambda execution.
> Add Shipping View for HCT Dashboard Data Pulls

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
An unmapped vaccine value was received for the Pfizer bivalent booster, adding here as CVX code 300 based on codes available from CDC (https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html).
> Add new vaccine value to map for UW retros ETL

- lib/seattleflu/id3c/cli/command/etl/__init__.py
Adding newly encountered value 'another race' from UW retrospective data to Redcap DET ETL race mapping function.
> Add new value to race map

- lib/seattleflu/id3c/cli/command/etl/__init__.py
Adding newly encountered value 'alaska native' from UW retrospective data to Redcap DET ETL race mapping function.
> Add another new value to race map

- lib/seattleflu/id3c/cli/command/clinical.py
Original implementation of the PHSKC ETL assumed that barcodes and CID values would always be provided as uppercase. This turned out to not be the case, and this caused many samples from October 2022 to not be linked to the associated metadata. This change forces all columns which will be compared for metadata associations to be uppercase.
> Force PHSKC Barcode and CID Comparisons to be Uppercase

- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
Some PHSKC records were coming through with non breaking spaces as the data for certain clinical fields. This caused issues with the mapper, which assumed that any strings should have some valid data in them. This change removes that assumption, instead treating strings that have been stripped empty as `None` type mappings.
> Treat Empty Strings as None in Clinical ETL

- lib/seattleflu/id3c/cli/command/clinical.py
Deprecates our use of the aliquoting sheets during the PHSKC clinical parsing routine in favor of making calls to the LIMS API in order to fetch the sample identifiers for records based on PHSKC CIDs. 
Adds a function that prepares LIMS API requests with HMAC signing. This function can be used by other routines as we remove all uses of the aliquoting sheets from our processes.
Must be merged alongside https://github.com/seattleflu/backoffice/pull/362
> Use LIMS API for PHSKC Metadata Parse and Sample Matching

- lib/seattleflu/id3c/cli/command/clinical.py
There was a bug affecting ingestion of 63 records for the PHSKC rework that dropped records if they had a null value for one of their identifiers. A single null identifier isn't an issue, and if all three of a records' identifiers are null it will still be dropped.
An additional bug casted the `census_tract` field to an integer instead of a string, which had unintended downstream ramifications during the FHIR ETL.
> PHSKC ETL Bugfixes

- .github/workflows/ci.yaml
- lib/seattleflu/id3c/cli/command/etl/__init__.py
Adds a new race mapping, `native hawaiian` to our clinical ETL. This race mapping was present before without a space, but a new value parsed out by our ETL includes a space.
> Add `Native Hawaiian` Race to Clinical ETL

- .github/workflows/ci.yaml
Prod currently uses python 3.9, and versions 3.6 and 3.7 are causing compatibility issues. Also making this change in ID3C.
> Drop python 3.6 and 3.7 from CI checks

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
- lib/seattleflu/id3c/cli/command/etl/clinical_retrospectives.py
- lib/seattleflu/id3c/cli/command/etl/redcap_map.py
Add clinical commands parse-kp2023, match-kp2023.
Update etl clinical command to process output from clinical commands with the FHIR standard.
Fix drop_missing_rows in clinical commands, which was not returning result as intended.
Note that other steps in the ETL routine such as downloading metadata from s3, deciding which csv(s) to parse, and selecting only new or changed data for upload to id3c, will be handled in backoffice.
> Add KP2023 ETL routine

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
Validate input metadata spreadsheet, strip aliquot number from collection id if present, and assign ambiguous flu vaccine names as unspecified when creating FHIR bundle.
> KP2023 ETL input validation

- lib/seattleflu/id3c/cli/command/etl/redcap_det_uw_retrospectives.py
Note that the new value in REDCap is "covid-19 pfizer mrna 2023-24 12 yrs and older (comirnaty)" and the CVX code assigned in this update is 309, which maps to the CDC description "Pfizer Fall 2023 12 years and older," without the name Comirnaty. However, the downloadable table [here](https://www.cdc.gov/vaccines/programs/iis/downloads/Fall-2023-COVID-19-Vaccine-Codes-Crosswalk-20230906.xlsx) confirms that 309 is the correct code for this vaccine.
> Add Pfizer fall 2023 12+ covid booster to redcap-det uw-retros

- lib/seattleflu/id3c/cli/command/etl/clinical.py
- lib/seattleflu/id3c/cli/command/etl/clinical_retrospectives.py
Previously, encounter_status was assigned as finished for records missing an encounter_status value, but an error was thrown for records missing the encounter_status field entirely. Now, encounter_status is assigned as finished if the value or field is missing.
> Clinical ETL: assign encounter_status as finished for records missing encounter_status field

- lib/seattleflu/id3c/cli/command/clinical.py
- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/clinical.py
Add newly encountered ethnicity values to ethnicity mapper.
For KP2023-specific functions that create ICD-10 and symptom condition resources, use the create_codeable_concept function to create the code entry, so that these condition resources can be correctly parsed by the fhir etl job.
> Clinical ETL: Update ethnicity mapper and fix codeable concepts

- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/redcap.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_asymptomatic_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_kiosk.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_and_home_flu.py
- lib/seattleflu/id3c/cli/command/etl/redcap_det_swab_n_send.py
- lib/seattleflu/id3c/cli/command/etl/redcap_map.py
Restoring 3 Swab and Send ETLs and the Kiosk ETL (which were previously dropped) to ingest addition fields requested by the Chu lab. In addition to the fields below, Spanish responses which were previously skipped in the Kiosk ETL will now be ingested.
Swab-n-send ETL
- income_levels
- insurance
- smoke_9a005a
- chronic_illness
- housing_type
- agegroups
- regular_activities_0
- school_interference_0
- activities_impacted_0
- regular_activities_1
- activities_impacted_2
- school_interference_1
- work_impact
- child_daycare
Swab-n-send + home flu ETL
- income_levels
- insurance
- smoke
- chronic_illness'
- agegroups
- regular_activities_0
- school_interference_0
- activities_impacted_0v2
- regular_activities_1
- activities_impacted_2
- school_interference_1
- work_impact_0
- work_impact
- …
> Restore Swab and Send and Kiosk ETLs

- lib/seattleflu/id3c/cli/command/clinical.py
Read in census tract as string in order to preserve leading 0s.
> parse-kp: read census tract as string

- Pipfile.lock
- lib/seattleflu/id3c/cli/command/etl/__init__.py
- lib/seattleflu/id3c/cli/command/etl/clinical_retrospectives.py
- setup.py
- Add "no_response" to etl race map
- Add "kp_2" to site map, mapping to KaiserPermanente
> Kp2023 race and site updates
